language: scala

scala:
  - 2.12.10

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

env:
  global:
    - secure: "GJmLXsXcReEvMd2H8aFMwPcI5rHWyLKMEckap+bM8Rd4L2QMteEtqnhuXx/782MPFZdzwUWL4vZkq5NtYMBdTXxnlb2zTiL8yoARWKDcmwJzIzoqyGPdY7qjnJtFVhz58QL8lOFGynSt9tZVk9E2xOsQ54vwQhq2AXM9nmmPh55SQ4txW8wm30d5TTgh9ZlYRQthu4F2ELNYb2ZZfLRwSXBkzO8/xeSyOyixkc0mjabWEGRD+sb+AFVDbgKwx8cPdnWMxEPf3TZnJnS0OP5mfIUCpCxklO4hVP3SOS6+g3sWJNdHEvtyZA8hIkotvHvLZaiIbe2EI/xOyxo+hO8xg6lVFwUHCgR2mcYoEPg9jMG7fQD9679vgvems3QIF6OlGuh7aMJkxxoJvGIDxfbEM1jal90elaDdArKtATookXwhXMKk4Z7nVR3OVoAQ7sP67I5U6TR6DX297R4NyugwUqYWytfeeUt2HV3mSY8HOGNra/f+P7uRX8eb69kLykvB6F6XW0wQ5GhrN592+ZKwXgrWtq/kBI3eWT2z0uBYJxP2kXg2F8aHLR88LMt3pVHckqxP4xXMQmqWXzJKMJPKuR7iVh7ykVQ0RkLCGoQKqgcOeyXygjLHhwY9+g57pjqFCuGKvdN1SC++sx1X/ypnekG2XK3BpsdfqVeG8rzig1c="
    - AWS_REGION=us-west-2

jdk: openjdk8

script:
  - sbt test scripted

before_deploy:
  - mkdir -p $HOME/.bintray
  - openssl aes-256-cbc -K $encrypted_d97b0ac93b8b_key -iv $encrypted_d97b0ac93b8b_iv -in .credentials.enc -out $HOME/.bintray/.credentials -d

deploy:
  - provider: script
    script: .travis/release.sh
    on:
      branch: master
      scala: 2.12.10
      condition: $(git log -n1 --format=format:"%an") != "Dwolla Bot"
