language: scala

script: sbt ++$TRAVIS_SCALA_VERSION pipeline

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

matrix:
  include:
  - env: SBT_VERSION="0.13.16"
    jdk: openjdk7
  - env: SBT_VERSION="1.0.0-RC3"
    jdk: oraclejdk8
script:
  - sbt "^^${SBT_VERSION}" pipeline

before_deploy:
  - mkdir -p $HOME/.bintray
  - openssl aes-256-cbc -K $encrypted_d97b0ac93b8b_key -iv $encrypted_d97b0ac93b8b_iv -in .credentials.enc -out $HOME/.bintray/.credentials -d

deploy:
  provider: script
  script: sbt "^^${SBT_VERSION}" publish
  on:
    branch: master
